### ISSUE TITLE
point commands for more modules

### ISSUE THREAD

**Issue by svineet** [apertium/phenny#150]
As part of GCI I built point commands like .awik Begiak -> svineet for wikitonary, wikipedia and apertium wiki. Would be nice if we ported this to other modules like:
- Urban Dictionary (.urb)
- Google (.g)

Please add a comment as to which modules need this.

**Comment by svineet** [comment]
I will work on this soon, when I am free

**Comment by wei2912** [comment]
It'd be good if you can look through the list of modules and see which ones should have point commands. Even better, find a way to have this apply to all modules (this would be difficult but is probably the best solution).

**Comment by svineet** [comment]
As the point commands are used to point new users/users in need of help to reference material online I don't think generalizing it for all commands will be a good solution. Instead only a small group of commands should have it.

**Comment by Androbin** [comment]
@wei2912 How would that look like conceptually?

**Comment by Androbin** [comment]
@wei2912 How would that look like conceptually?

**Comment by gstark0** [comment]
I'm also interested, seems cool idea.

**Comment by Androbin** [comment]
Let's just make sure we don't end up with something like #131 again.

**Comment by Androbin** [comment]
For each command, we could register a "twin" whose regex has `\s(->|→)\s(\S*)` added to it.
@svineet How about setting `point = True` on the function to enable this?

**Comment by wei2912** [comment]
Seems like a desirable solution to me. Having the flexibility to decide if the command is "point"able would be a better solution than a catch all.
