### ISSUE TITLE
Apertium wiki pages that begiak doesn't do a good job with

### ISSUE THREAD

**Issue by Leeyp** [apertium/phenny#151]
begiak doesn't work well on these 11 apertium wiki examples I have found, and these can be generalized into 4 cases as described below. The sample output of the examples can be found in this paste: http://paste2.org/bM2EwkAV
## Case 1: Navigation info returned

This problem invariably happens when there is the navigation UI at the side of the page, as can be seen on the main page or highlighted in this screenshot. 
![image](https://cloud.githubusercontent.com/assets/2010527/11765464/b1f3dd06-a193-11e5-8c4c-7220ff8f538f.png)

_Affected URLs_:
- http://wiki.apertium.org/wiki/Main_Page
- http://wiki.apertium.org/wiki/Installation
- http://wiki.apertium.org/wiki/Kazakh

_Example:_
    &lt;darkgaia&gt; .awik Main Page
    &lt;begiak&gt; " Home Page •  Bugs •  Wiki •  Chat" - http://wiki.apertium.org/wiki/Main_Page
## Case 2: Second Line Unintelligible Result

_Affected URLs_: http://wiki.apertium.org/wiki/Apertium_New_Language_Pair_HOWTO
                    http://wiki.apertium.org/wiki/List_of_symbols
                    http://wiki.apertium.org/wiki/List_of_dictionaries
This problem happens when the second line or paragraph of the wiki module is a navigation link, title, or a non-descriptive sentence about the page that does not give any hint as to what the page is about. It appears that the begiak module only reads the first sentence of the second paragraph of an Apertium wiki page.
_Example:_ <darkgaia> .awik Apertium_New_Language_Pair_HOWTO
<begiak> "Apertium New Language Pair HOWTO" - http://wiki.apertium.org/wiki/Apertium_New_Language_Pair_HOWTO
## Case 3: Wrong Second Line Result

_Affected URLs_: http://wiki.apertium.org/wiki/Trunk
                    http://wiki.apertium.org/wiki/Incubator
                    http://wiki.apertium.org/wiki/Staging
                    http://wiki.apertium.org/wiki/Monodix_basics
This problem happens when the description of the wiki page is placed on the first paragraph instead of the second. Because the begiak module only reads the first sentence of the second paragraph, a result will be returned that could hint about the information in the page (it is intelligible), but it is not the correct definitive description of the page.
_Example:_ <darkgaia> .awik trunk
<begiak> "All trunk pairs should have had at least one release." - http://wiki.apertium.org/wiki/Trunk
## Case 4: Section after First Line

If the first section (usually the description) is only one paragraph long, before proceeding to a new section, this may cause unintelligible results as well. Begiak will move on to the first sentence of the next section, or, if that section is also only one line long, will proceed to the following section, particularly striking in the "Apertium Simpleton UI" page, which can be particularly problematic.
_Affected URLs_:
- http://wiki.apertium.org/wiki/Apertium_Simpleton_UI
- http://wiki.apertium.org/wiki/Translation_quality_statistics
- http://wiki.apertium.org/wiki/Apertium-kaz

_Example:_ <darkgaia> .awik Apertium Simpleton UI
<begiak> "The Windows build should work on Vista and newer." - http://wiki.apertium.org/wiki/Apertium_Simpleton_UI

**Comment by jonorthwash** [comment]
A recent example:
```
(23:54:58) firespeaker: .awik Languages
(23:55:01) begiak: "New monolingual packages should be developed in incubator until they're minimally useful, at which point they can go in /languages/" - http://wiki.apertium.org/wiki/Languages
```
