### ISSUE TITLE
Conflict with `archwiki.py`

### ISSUE THREAD

**Issue by wei2912** [apertium/phenny#197]
https://github.com/goavki/phenny/blob/master/modules/archwiki.py has the command `awik` which conflicts with our command for Apertium wiki. Should this module be disabled/removed? It doesn't seem to interfere with the normal functioning of begiak unless the module is reloaded.

**Comment by Putti** [comment]
I think the command could be just renamed as archwiki or similar.

**Comment by jonorthwash** [comment]
Agreed.  And maybe ours should be `.apwik` for good measure?

**Comment by Putti** [comment]
No need to change .awik to .apwik in my opinion, people are used to it already.

**Comment by jonorthwash** [comment]
But what about for upstream users?

**Comment by Putti** [comment]
You mean merging the code to upstream? Like would some problems arise in doing that? Or what do you mean?

**Comment by Putti** [comment]
And who do you mean with upstream users?

**Comment by jonorthwash** [comment]
Yeah, I mean when merging into upstream, if anyone wants functionality of both, then there will be a problem.

**Comment by unhammer** [comment]
Merge from a branch where you change that bit? I assume we have to keep *some* differences, since not everything is configurable

**Comment by jonorthwash** [comment]
We don't really have a strategy in place for how to deal with that.  Are you suggesting we keep an Apertium/begiak-specific branch?  If so, I don't get how that helps when we merge into it from upstream...

**Comment by Putti** [comment]
Just a note: the upstream looks pretty abandonded... But maybe some day it will arise from the darkness and we can merge the changes.

**Comment by Androbin** [comment]
Removed in #441
