### ISSUE TITLE
Reload quirks

### ISSUE THREAD

**Issue by shardulc** [apertium/phenny#249]
In most use-cases, `reload.py` can reload modules with no issues. However, consider the Wikipedia module: some commands like `.wik` are called directly, while others, like detecting Wikipedia URLs and providing snippets, are called from `head.py`. For this the `head.py` file has a line saying `import wikipedia`. When the Wikipedia module is reloaded, commands like `.wik` change their behavior appropriately, but the `wikipedia` that `head.py` knows about doesn't change.

I feel that the expected behavior is that *all* instances of the module change upon reloading. To achieve this, perhaps a different method of reloading is required, but I can't think of an elegant one: thoughts?

**Comment by wei2912** [comment]
Good point there. I am not sure about how other IRC bots perform reloading of modules, but they probably do not use the Python module system.

**Comment by Androbin** [comment]
Why doesn't `reload.py` just use the `reload` builtin function?

**Comment by shardulc** [comment]
@Androbin The relevant code has last been changed by me, and I do not recall why I chose to use `imp.load_source` over `reload`. However, I do recall that I debated it, and my decision was based on the fact that "When a module is reloaded, its dictionary (containing the module’s global variables) is retained" (from the Python docs) and some issues with the `git.py` module.

**Comment by Androbin** [comment]
@shardulc Since the issue is to get rid of old references, what would a cold-start look like?
Meaning, could we programatically tear down all modules and reload them from scratch?

**Comment by Androbin** [comment]
How about moving all imports into a separate function `import_modules`?
* Reload modules
* Call `import_modules` for all modules
* Call `setup` for all modules

**Comment by Androbin** [comment]
Or maybe we can iterate over a modules imports and reload them for it?

**Comment by Androbin** [comment]
Maybe reloading individual modules isn't quite infeasible.

> perhaps a different method of reloading is required

In #398 I am able to safely modify files and restart the entire python process.
