### ISSUE TITLE
Tests(3) failing for Calc module

### ISSUE THREAD

**Issue by muhammad-mullboccus7** [apertium/phenny#263]
Failing modules: calc.py
https://github.com/goavki/phenny/blob/master/modules/test/test_calc.py
- Failing test: test_c
     The error is on line 510 in this build: ""test_c (phenny.modules.test.test_calc.TestCalc) ... FAIL"

- Failing test: test_c_scientific
     The error is on line 512 in this build: ""test_c_scientific (phenny.modules.test.test_calc.TestCalc) 
     ... FAIL"

- Failing test: test_c_sqrt
     The error is on line 513 in this build: ""test_c_sqrt (phenny.modules.test.test_calc.TestCalc) ... 
     FAIL"

Build log: https://travis-ci.org/goavki/phenny/jobs/309867406

**Comment by shardulc** [comment]
Tests no longer fail (via #274), but #271 notes the need to fix this.

**Comment by Androbin** [comment]
@shardulc now we got #307.

**Comment by Androbin** [comment]
@shardulc Should be resolved as of #307?

**Comment by Androbin** [comment]
Fixed in #307
