### ISSUE TITLE
Tests(2) failing for Imdb module

### ISSUE THREAD

**Issue by muhammad-mullboccus7** [apertium/phenny#266]
Failing module: Imdb.py
https://github.com/goavki/phenny/blob/master/modules/test/test_imdb.py

- Failing test: test_c_imdb
     The error is on line 546 in this build: ""test_imdb (phenny.modules.test.test_imdb.TestImdb) ... 
     ERROR"

- Failing test: test_imdb_search
     The error is on line 548 in this build: ""test_imdb_search 
     (phenny.modules.test.test_imdb.TestImdb) ... ERROR"

Build log: https://travis-ci.org/goavki/phenny/jobs/309867406

**Comment by shardulc** [comment]
As outlined in #274, we need an API key for IMDB.

**Comment by Androbin** [comment]
With #317 it doesn't require an `API_KEY` anymore.

**Comment by Androbin** [comment]
Fixed in a9d69c82036cc003f9a437dd301bf2282cf2e6b3. Also doesn't need `API_KEY` anymore.
