### ISSUE TITLE
Replacement for search module

### ISSUE THREAD

**Issue by wei2912** [apertium/phenny#271]
The search module uses the deprecated Google Web Search API, and no longer works (https://github.com/goavki/phenny/issues/268). A possible replacement for the module could be DuckDuckGo's [Instant Answer API](https://duckduckgo.com/api), which does not provide full search results, but seems to be the best free alternative.

The following requirements should be met (taken from the page, "us" refers to DuckDuckGo):
1. Attribution in each place you use our API for both us and any underlying source. For the source, you can link to the source's relevant detail page. For us, you can say Results from DuckDuckGo with our logo (and link to the specific result page).
2. Non-commercial use unless you get email approval from us (though we're generally fine with anything that isn't sketchy).
3. Use a descriptive t parameter, i.e. append &t=nameofapp to your requests.

**Comment by shardulc** [comment]
The calculator module should also be rewritten to use a different service, or perform calculations in-house.

**Comment by shardulc** [comment]
#325 implements DDG search but I'm not sure it satisfies the requirements above.
 1. Search results are in the form "Apple A deciduous tree in the rose family best known for its sweet, pomaceous fruit, the apple. - https://duckduckgo.com/Apple". This does not link to the source page, only to the search page. I guess the image logo requirement doesn't apply to us.
 1. Satisfied.
 1. Not implemented yet, does `t='{:}-phenny'.format(phenny.owner)` work?

**Comment by gstark0** [comment]
@shardulc that's because DDG Instant Answers limitations, we can't get the external links from it.
> This API does not include all of our links, however. That is, it is not a full search results API or a way to get DuckDuckGo results into your applications beyond our instant answers. Because of the way we generate our search results, we unfortunately do not have the rights to fully syndicate our results, free or paid.
That's quote from DDG API website.
Also, if you want to search for company, you have to be more specific -> ".search Apple Inc" does the job good :)

**Comment by shardulc** [comment]
Yup, it will probably be hard to get the 'source URL' for DDG results. I was just wondering because that's what the terms in the first comment seemed to say.

> if you want to search for company

No I was talking about the DDG logo actually :smile:

**Comment by gstark0** [comment]
@shardulc 
> No I was talking about the DDG logo actually
I understood that when I read it again, sorry :)

But yeah, some sources are from e.g wikipedia or github, and if they are, the source is included :)

**Comment by Androbin** [comment]
> This API does not include all of our links

There may not be an API endpoint for it.
But we can do some web scraping.

**Comment by wei2912** [comment]
I'd recommend that we implement the new solution with a fully-featured search e.g. [Bing Search API](https://azure.microsoft.com/en-us/pricing/details/cognitive-services/search-api/), instead of using DuckDuckGo's Instant Answers API, as it really isn't that helpful.
