### ISSUE TITLE
Add website translation by command

### ISSUE THREAD

**Issue by gstark0** [apertium/phenny#300]
How about adding whole website translation to begiak? Something like:
.tweb eng-spa google.com or .t web eng-spa google.com
And begiak would generate link to translated website:
 https://www.apertium.org/index.eng.html?dir=eng-spa&qP=google.com#webpageTranslation
I think it would be pretty useful :)

**Comment by Androbin** [comment]
So, basically, you would have a template string and just substitute the arguments passed?
How about printing the raw text directly into the chat? Let's say, using the `more` module?

**Comment by ImmortalShox** [comment]
@Androbin That could be pretty good idea as additional parameter :)

**Comment by ImmortalShox** [comment]
@Androbin But it would need communicate with Apy somehow I guess?

**Comment by Androbin** [comment]
> But it would need communicate with Apy somehow I guess?

No deal, we can access https://www.apertium.org/apy/translatePage?langpair=eng%7Cspa&markUnknown=no&url=example.com

**Comment by Androbin** [comment]
See [git.py](https://github.com/goavki/phenny/blob/master/modules/git.py#L91) as reference for parsing.

**Comment by ImmortalShox** [comment]
@Androbin Cool, I will take a look at it :)
