### ISSUE TITLE
.time gives the wrong time for some zones

### ISSUE THREAD

**Issue by JPJPJPOPOP** [apertium/phenny#304]
For some reason, begiak gives the wrong time for PST.

![screen shot 2017-12-29 at 11 09 41 pm](https://user-images.githubusercontent.com/13565154/34452146-9e2f9768-eced-11e7-8aaa-aa6ec3b983a1.png)

Seems like 8 hours off.

IST seems to be off too.
![screen shot 2017-12-29 at 11 19 51 pm](https://user-images.githubusercontent.com/13565154/34452191-d93ebe50-ecee-11e7-8f01-c597074c1af9.png)
![screen shot 2017-12-29 at 11 20 14 pm](https://user-images.githubusercontent.com/13565154/34452193-dc0dfc40-ecee-11e7-9295-fcf9f8a5258c.png)

**Comment by Androbin** [comment]
![node](https://user-images.githubusercontent.com/16437156/34506900-04c3a49c-f031-11e7-986f-25e45e212556.png)

**Comment by Androbin** [comment]
See #322. Should be fixed by #326.
