### ISSUE TITLE
test_locations is broken

### ISSUE THREAD

**Issue by Androbin** [apertium/phenny#305]
[This test](https://github.com/goavki/phenny/blob/master/modules/test/test_weather.py#L22) keeps failing due to the data source constantly changing its output.
This can often block any innocent change.

We should either remove, skip or fix this test.

**Comment by gstark0** [comment]
IMHO we should just edit so instead of post codes it would search and check by location, like it is with Berlin in that testing unit.

**Comment by Androbin** [comment]
I think we need to rethink our assumptions for the tests some time.

**Comment by Androbin** [comment]
`display_name` is actually unused anyway.
But `latitude` and `longitude` aren't tested at all.
