### ISSUE TITLE
git module having trouble with some pushed messages

### ISSUE THREAD

**Issue by jonorthwash** [apertium/phenny#329]
We're getting this for a lot of stuff now:
```
(00:49:11) begiak: Something went wrong: dict_keys(['pusher', 'before', 'forced', 'sender', 'compare', 'base_ref', 'after', 'organization', 'ref', 'commits', 'created', 'head_commit', 'deleted', 'repository'])
```

**Comment by jonorthwash** [comment]
@Androbin

**Comment by Androbin** [comment]
This should be a harmless message since it only indicates that we generated no messages.
First of all, we should probably produce a more informative error message.

**Comment by Androbin** [comment]
I think I know what's going on now.

**Comment by Androbin** [comment]
`push` events on forks are ignored by default.

**Comment by Androbin** [comment]
@sushain97 /cc

**Comment by Androbin** [comment]
@shardulc /cc #275

**Comment by sushain97** [comment]
That sounds like proper behavior to me. Let's just get rid of the error message in IRC.

**Comment by Androbin** [comment]
@sushain97 I will send a PR no suppress this message if we already know the payload was dealt with.

**Comment by Androbin** [comment]
I just updated PR #332 to suppress this message if we already know the payload was dealt with.

**Comment by jonorthwash** [comment]
Getting this on most (all?) git hook payloads:
```
----------------------------------------
Exception happened during processing of request from ('192.30.252.36', 40256)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
TypeError: 'MyHandler' object is not callable
----------------------------------------
```

**Comment by Androbin** [comment]
Could you check if 9a843dacf1b29848db57ef036d79d7045bc28002 fixed this?

**Comment by Androbin** [comment]
@jonorthwash Could you check if 9a843dacf1b29848db57ef036d79d7045bc28002 fixed this?

**Comment by Androbin** [comment]
Fixed `TypeError: 'MyHandler' object is not callable` in 856bbc32ab11b5d1606be219cb96c1135b86a211.
