### ISSUE TITLE
Begiak gives .awik twice

### ISSUE THREAD

**Issue by gstark0** [apertium/phenny#375]
<img width="1009" alt="screen shot 2018-01-15 at 21 33 08" src="https://user-images.githubusercontent.com/25964807/34960622-e8c16648-fa3b-11e7-912d-5a4ddd999604.png">

**Comment by shardulc** [comment]
I don't think so. Why would `archwiki.py` print an article from the Apertium wiki?

**Comment by Androbin** [comment]
Why would two different modules handle `.awik` commands?

**Comment by shardulc** [comment]
See also #197. But that's likely different from what's causing the double output.

**Comment by jonorthwash** [comment]
Applies to `.w` too.

```
(10:39:59) firespeaker: .w light verb
(10:40:00) begiak: light verb — noun: 1. linguistics: A thematically incomplete verb which only in combination with a predicative complement qualifies as a predicate
(10:40:02) begiak: light verb — noun: 1. linguistics: A thematically incomplete verb which only in combination with a predicative complement qualifies as a predicate
```

**Comment by Androbin** [comment]
Is there any chance for a module / function to be registered twice?

**Comment by jonorthwash** [comment]
Maybe?  How might we identify that?

My thought is that this was introduced in the generalised output reduction code.

**Comment by Androbin** [comment]
I would suspect it has something to do with the reload module?

**Comment by jonorthwash** [comment]
The reload module was heavily modified recently too, so it could well be related to those changes.

**Comment by Androbin** [comment]
The `bot.py` module holds the dictionary in question.
It should only be able to hold one value per key.
Is there any chance the whole module is used twice? Probably not?
Anyhow, I can't imagine how this would have been provoked by the logging commit.

**Comment by Androbin** [comment]
Okay, I debugged the hell out of this.
The `head.py` module has `from modules.apertium_wiki import awik`.
This means that the `awik` function is top-level in `head.py`.
As a result of that, the same function is registered in two modules.

**Comment by Androbin** [comment]
Importing a function is basically equivalent to declaring it, so we can't differentiate between them.
We could either change the import or remove the import at the end of the module.

**Comment by Androbin** [comment]
And maybe we can add a CI test to catch such problematic imports.
