### ISSUE TITLE
Remove "(posted: 11 months ago by XXX)"

### ISSUE THREAD

**Issue by flammie** [apertium/phenny#381]
```
16:04 < spectie> https://developers.google.com/open-source/gsoc/help/student-stipends
16:04 < begiak> [ Student Stipends  |  Google Summer of Code  |  Google Developers ] (posted: 11 months ago by Flammie)
```

This is very misleading and highlights people unnecessarily. I'm guessing it's supposed to say who has also posted the link but it seems to me like the person has posted the page mentioned to the internet! I did not post anything about student stipends to gsoc site.

**Comment by Androbin** [comment]
Should the entire `posted` module be removed?

**Comment by flammie** [comment]
Unless someone has an use case for it, I think it should go, I guess it might be useful for other kind of social channels (encouraging users not to repost same links maybe), even if it is retained it would be better reworded and without nick mention.

**Comment by Androbin** [comment]
@sushain97 Any objections?
