### ISSUE TITLE
python3.5 incompatibilities?

### ISSUE THREAD

**Issue by jonorthwash** [apertium/phenny#383]
@sushain97 thinks the following issues have arisen because of an upgrade from python3.4 to python3.5, meaning that begiak was never made compatible with 3.5:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
TypeError: 'MyHandler' object is not callable
```

`seen.py / f_note` raises `ERROR: db type could not be determined`

**Comment by jonorthwash** [comment]
Every time someone (me?) says something, we get the `db type error`.  Every time a git webhook happens, we get a `MyHandler` error.

We also (randomly?) just got this:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 1180, in run
    self.function(*self.args, **self.kwargs)
  File "/home/begiak/phenny/modules/mailing_list.py", line 95, in check_mail
    message = format_email(e, name)
  File "/home/begiak/phenny/modules/mailing_list.py", line 67, in format_email
    subject = ''.join([unicode(t[0], t[1] or 'utf-8') for t in decode_header(subject)])
  File "/home/begiak/phenny/modules/mailing_list.py", line 67, in <listcomp>
    subject = ''.join([unicode(t[0], t[1] or 'utf-8') for t in decode_header(subject)])
NameError: name 'unicode' is not defined
```

**Comment by sushain97** [comment]
`s/unicode/str`. idk how that code survived this long.

**Comment by sushain97** [comment]
requesthandler/server class interaction should look more like in https://github.com/apertium/apertium-on-github/blob/master/sync.py#L357

**Comment by sushain97** [comment]
@Androbin could you fix this since you wrote it originally?

**Comment by Androbin** [comment]
The nightly build of #382 seems to fail because of changes in some dependencies.
The issue with `MyHandler` seems to be ditto.
I don't know about the databases.
Investigating...

**Comment by Androbin** [comment]
The errors don't get less. They seem to be all related to the `urllib3` module:
```
  File "/media/androbin/Daten/git/phenny/web.py", line 10, in <module>
    import requests
  File "/usr/local/lib/python3.5/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/local/lib/python3.5/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 58, in <module>
    class ConnectionPool(object):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 65, in ConnectionPool
    QueueCls = queue.LifoQueue
AttributeError: module 'queue' has no attribute 'LifoQueue'
```

**Comment by Androbin** [comment]
The latter seems to be due to name shadowing by our `queue` module...
Why is this happening NOW?

**Comment by Androbin** [comment]
The db error seems to be thrown by the `pickle` module because it messes with the file name.

**Comment by Androbin** [comment]
Do we still need `seen.py > f_note` (deprecated, dysfunctional) or can we drop it?

**Comment by Androbin** [comment]
The `unicode` global function was removed. I will rewrite that line.

**Comment by Androbin** [comment]
The `unicode` global function was removed.
I rewrote that line and thus fixed it in 2a4d59e87c33f0aa19e685fd701067e76f5aa919.

**Comment by Androbin** [comment]
@sushain97 The `server_bind` method in your example:
```
    def server_bind(self):
        self.socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self.socket.bind(self.server_address)
```
... looks just like the `server_bind` in `tools.py > PortReuseTCPServer` used.

**Comment by sushain97** [comment]
The server_bind isn't the problem. `https://github.com/apertium/phenny/blob/master/modules/git.py#L398` isn't valid. pass `pheny` to the server instead, not the handler.

**Comment by Androbin** [comment]
No, the `PortReuseTCPServer` doesn't know how to deal with it.
It just gets `MyHandler` initialized with `phenny`.
I don't see how the `RequestHandler` is different?.

**Comment by Androbin** [comment]
The `nightly` build of #382 fails for equally version suspicious reasons.

**Comment by sushain97** [comment]
> No, the PortReuseTCPServer doesn't know how to deal with it.
Then subclass it and figure it out there. The request handler gets initialized with each request. A class should be passed to the server, not an instance. Look at sync.py.

**Comment by Androbin** [comment]
Okay, got it.

**Comment by Androbin** [comment]
Oops, messed that up in 7ebba9bf4a833da07cbb727913d73ff8525d1015. Fixed in 856bbc32ab11b5d1606be219cb96c1135b86a211.

**Comment by Androbin** [comment]
All mentioned issues are fixed now:
- [x] TypeError: 'MyHandler' object is not callable (856bbc32ab11b5d1606be219cb96c1135b86a211)
- [x] ERROR: db type could not be determined (78da9020f2afb5e2a9c3840b740a0be89026ab6a)
- [x] NameError: name 'unicode' is not defined (2a4d59e87c33f0aa19e685fd701067e76f5aa919)

**Comment by sushain97** [comment]
Awesome! @jonorthwash could you update begiak?
