### ISSUE TITLE
gives error every time someone gets op or voice

### ISSUE THREAD

**Issue by jonorthwash** [apertium/phenny#384]
```
* ChanServ gives voice to jonorthwash
<begiak> OSError: [Errno 98] Address already in use (file "/home/begiak/phenny/tools.py", line 92, in server_bind)
```

**Comment by Androbin** [comment]
May I ask: How exactly does someone get op or voice?

**Comment by Androbin** [comment]
The error comes from trying to restart the `git` hook via `setup_server` before it is shut down.

First, we should consider changing the triggers:
```
setup_server.rule = '(.*)'
setup_server.event = 'MODE'
```

Second, the condition check was (temporarily) disabled some time ago:
```
if not httpd or True:
```

**Comment by Androbin** [comment]
@jonorthwash How about calling `setup_server` from `setup` instead?
Possibly with a flag to be set in the configuration.
And of course, re-enable the condition check.

**Comment by Androbin** [comment]
Is it correct that the change of channel operator triggers the `MODE` event?

**Comment by jonorthwash** [comment]
Seems to've worked.
