### ISSUE TITLE
Update awikstats for GitHub

### ISSUE THREAD

**Issue by ftyers** [apertium/phenny#389]
I get this when I try:

```
<begiak> INFO:root:Login as StemCounterBot succeeded
<begiak> ERROR:root:Unable to retrieve incubator root list: Command 'svn list --xml https://svn.code.sf.net/p/apertium/svn/incubator' returned non-zero exit status 1
<begiak> ERROR:root:Unable to retrieve incubator root list: Command 'svn list --xml https://svn.code.sf.net/p/apertium/svn/incubator' returned non-zero exit status 1
<begiak> INFO:root:Acquired file counts {'stems': (36, ('36880', 'spectre360'), 'https://svn.code.sf.net/p/apertium/svn/incubator/apertium-grn/apertium-grn.grn.lexc'), 'vanilla stems': (36, ('36880', 'spectre360'), 'https://svn.code.sf.net/p/apertium/svn/incubator/apertium-grn/apertium-grn.grn.lexc'), 'rlx rules': (1, ('36880', 'spectre360'), 'https://svn.code.sf.net/p/apertium/svn/incubator/apertium-grn/apertium-grn.grn.rlx')}
<begiak> INFO:root:Creation of page Apertium-grn/stats succeeded (http://wiki.apertium.org/wiki/Apertium-grn/stats)
```

**Comment by sushain97** [comment]
https://github.com/apertium/apertium-stats-service is mostly complete.

after

https://github.com/apertium/apertium-stats-service/issues/10
and
https://github.com/apertium/apertium-stats-service/issues/7

are complete, we should just switch Begiak to use it and then it'll just be a thin wrapper over HTTP calls.

**Comment by ftyers** [comment]
@sushain97 how is that progressing?

**Comment by sushain97** [comment]
https://github.com/apertium/apertium-stats-service is ready for usage. It just needs to be run somewhere and then begiak code needs to be switched to use it.

**Comment by ftyers** [comment]
@sushain97 @TinoDidriksen can we run it on the Apertium server? ... @sushain97 can you switch begiak to use it ? -- is that a simple fix ?

**Comment by sushain97** [comment]
I think it would be about ~20 minutes of deleting code. Some of the code in SVN also needs to be moved into GH.

**Comment by jonorthwash** [comment]
Any updates on this?

**Comment by sushain97** [comment]
I started on it a couple weeks ago and then realized two things:

- the stats service didn't support vanilla stems
- the bot also handles coverage stats now

For the first, I implemented vanilla stem counting: https://github.com/apertium/apertium-stats-service/commit/4928b2ff308380d50f087b7bf829559fc3e25f1a

The second is unfortunately pretty involved so I decided the best course of action is to:

1. Bring in the bot script and coverage script from SVN into this repo.
2. Modify the begiak module to use the local versions from this repo and delete its reference to lexccounter.
3. Delete all the bot's scripts connections to lexccounter/manual parsing code and just make it request the stats service. For the coverage option, it would still hit the Python (I hadn't planned for this dependency).
4. Deploy the stats service on Tino's machine. (`git clone`, `docker build`, `docker run`).

**Comment by jonorthwash** [comment]
@sushain97, what's the status here?  @nu11us seems interested in a GCI task related to this.

**Comment by sushain97** [comment]
Step 4 is done. He can take up steps 1-3. There's some instability in the service due to a db lock poisoning issue but it doesn't crop up unless you throw 30+ simultaneous requests. There's an issue out to fix it that could also easily be a GCI task.
