### ISSUE TITLE
Update begiak via admin command

### ISSUE THREAD

**Issue by Androbin** [apertium/phenny#392]
Usage:
```
.upgrade <commit>
```

Example:
```
kevin: .upgrade 123456
begiak: You're no admin, kid.

sushain: .upgrade 654321
begiak: Wait for me to pull and restart...
```

**Spoiler:** There is a chance of it crashing the first few attempts.

**Comment by Androbin** [comment]
@sushain97 @jonorthwash What you think?

**Comment by jonorthwash** [comment]
Would be cool, but we have bigger fish to fry right now, I think...  I also wonder how safe it would be.

**Comment by jonorthwash** [comment]
Oh, and what's the number?

**Comment by Androbin** [comment]
> I also wonder how safe it would be.

The admin could be asked to sign a string with his private key.

> Oh, and what's the number?

As per the syntax `.upgrade <commit>`, it's the commit hash.

**Comment by Androbin** [comment]
Let me build a prove-of-principle first, then we can talk.

**Comment by Androbin** [comment]
```
$ ls
gen-key.sh  sign-msg.sh  verify-msg.sh
$ ./gen-key.sh 
$ ./sign-msg.sh '.upgrade 123456'
NAh2dXhHePjQs1SWOQkE4bEYC9JjUYy1/t4fqVkjlzjyMmR2uzDT6jC51RFXuBMCYCL17aDF4H3d+DAY+ce3gqQc+GXoaKmHOr/g0xwBA8yZvtChowN+pp5D4LPpylD/HXhTlcbMBoaAbIvyD5khN2rrQiFxPqYfvYNeCnXXNSc=
$ ./verify-msg.sh '.upgrade 123456' NAh2dXhHePjQs1SWOQkE4bEYC9JjUYy1/t4fqVkjlzjyMmR2uzDT6jC51RFXuBMCYCL17aDF4H3d+DAY+ce3gqQc+GXoaKmHOr/g0xwBA8yZvtChowN+pp5D4LPpylD/HXhTlcbMBoaAbIvyD5khN2rrQiFxPqYfvYNeCnXXNSc=
Verified OK
```

**Comment by Androbin** [comment]
I'm working on a prove-of-principle in #398.
