### ISSUE TITLE
Bring back Python3.4 tests

### ISSUE THREAD

**Issue by sushain97** [apertium/phenny#414]

**Comment by Androbin** [comment]
How about testing the following:
* oldest (3.4)
* newest (3.6)
* nightly

**Comment by sushain97** [comment]
Why? Just test 3.4, 3.5, 3.6 and nightly.

Use pip caching if the tests are too slow right now and we aren't yet. See
streamparser's Travis config for inspiration. We should also use
travis_retry to limit network issues.

**Comment by sushain97** [comment]
Looks like the only way to fix this is by monkey patching asynccore. Thoughts?

**Comment by sushain97** [comment]
(only during testing of course)

**Comment by Androbin** [comment]
> Looks like the only way to fix this is by monkey patching `asynccore`.

We could look at the diff between the library versions for 3.4 and 3.5 and applying whatever fixed it there.

**Comment by sushain97** [comment]
I don't think that's necessary. The fix is in the bug report you linked.

**Comment by Androbin** [comment]
Done. PR #416 now passes tests.
