### ISSUE TITLE
Python 3.4 asyncore mock issue

### ISSUE THREAD

**Issue by Androbin** [apertium/phenny#415]
#414 Tests fail for Python 3.4: https://travis-ci.org/apertium/phenny/jobs/357048685
Seems to be an issue with the `Mock` objects. Their `__getattr__` fall into an infinite loop.

**Comment by Androbin** [comment]
This seems to be a known bug in the Python 3.4 version of `asyncore`:
https://bugs.python.org/issue13103

**Comment by sushain97** [comment]
dup of #414. The reason I created we initially disabled Python 3.4 testing is because of this infinite loop...
