### ISSUE TITLE
Github issue creator command

### ISSUE THREAD

**Issue by sushain97** [apertium/phenny#433]
Something like:

```
begiak: apertium-html-tools: sushain97 [ dbebe23 ] assets/strings/szl.json, assets/strings/locales.json, assets/strings/README.md: Added Silesian localization (#326)
sushain: .issue apertium/phenny Commit messages with multiple authors showing the less relevant one
begiak: Issue created. You can add a description at https://github.com/apertium/phenny/issues/1234.
```

**Comment by Androbin** [comment]
We could either have a GitHub bot for all or each create a "Personal Access Token".

**Comment by sushain97** [comment]
We already have a bot: https://github.com/ApertiumBot. Let's reuse him. I can provide @jonorthwash with the access token. The issue contents can say who originally requested it in IRC.

**Comment by namanchikara** [comment]
I don't know if it's just me or the  https://github.com/ApertiumBot doesn't have any public repositories.

**Comment by namanchikara** [comment]
> We already have a bot: https://github.com/ApertiumBot. Let's reuse him them. I can provide @jonorthwash with the access token. The issue contents can say who originally requested it in IRC.

I don't know if it's just me or the https://github.com/ApertiumBot doesn't have any public repositories.

**Comment by sushain97** [comment]
Why would the bot have any repositories of its own?

**Comment by namanchikara** [comment]
Oh sorry, My bad. I'm new to this. I might apply for GSoc, hence I was going through 'issues' and 'code' of various repos. Anyway thanks for the fast reply.

**Comment by sushain97** [comment]
No worries!
