### ISSUE TITLE
More granular github issue event support

### ISSUE THREAD

**Issue by sushain97** [apertium/phenny#434]
We currently mention issue label changes and issue edits. I think these are pretty noisy and not really useful.

I would much rather mention a comment on an issue which we currently aren't.

Thoughts?

e.g.

```
[5:44pm] begiak: apertium-init: sushain97 * issue #42 "Ignore .prob on bilingual modules" unassigned  https://github.com/apertium/apertium-init/issues/42
[5:45pm] sushain: I find changes to labels and assignments of github issues getting posted much less useful than having comments mirrored
[5:48pm] begiak: apertium-init: sushain97 * issue #49 "¿<?xml for xml files?" edited  https://github.com/apertium/apertium-init/issues/49
[5:53pm] begiak: apertium-init: sushain97 * issue #36 "Set repository topic on create (apertium-incubator)" edited  https://github.com/apertium/apertium-init/issues/36
[6:04pm] begiak: phenny: sushain97 * issue #434 "Github module events to mention" opened  https://github.com/apertium/phenny/issues/434
[6:04pm] begiak: phenny: sushain97 * issue #434 "Github module events to mention" labeled with question https://github.com/apertium/phenny/issues/434
```

cc @jonorthwash @ftyers

**Comment by Androbin** [comment]
See #399 for ticket comments.

**Comment by sushain97** [comment]
I don't see ticket comments currently in IRC. Is begiak not updated to this repo's HEAD or is that change not live/merged?

**Comment by Androbin** [comment]
As per https://github.com/apertium/phenny/pull/422#issuecomment-408887463, we currently only get `push` and `issues` events.

**Comment by jonorthwash** [comment]
Uh, so should I update the config?  I don't know who decided on what's currently there, but it was probably set up that way for a reason.

**Comment by wei2912** [comment]
This issue is linked to https://github.com/apertium/phenny/issues/159.

**Comment by TinoDidriksen** [comment]
For issues, it should only message IRC on creation and replies. Potentially on closing. But certainly not on labeling, assigning, edits, or anything else.

**Comment by Androbin** [comment]
Then we need `"issues"` and `"issue_comment"` events and filter `"issues"` events by `"action"`:
- We want only `"opened"`, `"closed"` and `"reopened"`.
- We don't want `"assigned"`, `"unassigned"`, `"labeled"`, `"unlabeled"`, `"edited"`, `"milestoned"` and `"demilestoned"`.

**Comment by sushain97** [comment]
@Androbin would you mind leaving this for GCI for a little bit at least? I've created a task for it already.

**Comment by avyayv** [comment]
@Androbin I can fix this issue

**Comment by flammie** [comment]
While I don't mind ticket comments, they can be useful sometimes, the bots commenting pull requests are not very interesting to IRC I don't think, and have potential for lots of spam I'm afraid:

```
13:30  begiak> apertium-init: coveralls * comment created on pull request #61: ## Pull Request Test Coverage Report for [Build 
               85](https://coveralls.io/builds/20576619) * **1** of **1**   **(100.0%)**  changed or added relevant line in **1** file are covered. * No unchanged 
               relevant lines lost coverage. * Overall coverage remained the same at **72.656%** --- |  Totals | [![Coverage... 
               https://github.com/apertium/apertium-init/pull/61
13:30  begiak> apertium-init: coveralls * comment created on pull request #61: ## Pull Request Test Coverage Report for [Build 
               85](https://coveralls.io/builds/20576619) * **1** of **1**   **(100.0%)**  changed or added relevant line in **1** file are covered. * No unchanged 
               relevant lines lost coverage. * Overall coverage remained the same at **72.656%** --- |  Totals | [![Coverage... 
               https://github.com/apertium/apertium-init/pull/61
```

**Comment by sushain97** [comment]
I like ticket comments as well and agree with your comment. Let's open an issue to configure blacklist strings or something of that nature.
