### ISSUE TITLE
Develop module for Begiak that tracks GCI students

### ISSUE THREAD

**Issue by wei2912** [apertium/phenny#437]
As one of the Google Code-in tasks is to stay on the IRC channel for four hours, a module can be developed to track the time these students spend on the channel.

Just a few ideas:
1. Have students run a command `.gci full_name` to indicate that they are a GCI student with `full_name` being their name on the GCI website.
2. Time tracked should be cumulative.
3. Upon reaching four hours, the bot should send a message indicating that the student has successfully completed the task.

Any thoughts on this?

**Comment by wei2912** [comment]
@Androbin It should be persistent across disconnects and message target should be #apertium.

**Comment by wei2912** [comment]
To all mentors, let us know if there's an issue with the gci module.

**Comment by wei2912** [comment]
There seems to be a few bugs with the system and some changes are needed.

**Comment by Androbin** [comment]
@wei2919 Please elaborate

**Comment by wei2912** [comment]
Just a few remarks:
1. Students should not need to reveal their full names on IRC to complete the task.
2. Mentors should link students - that way, we get a bit more interaction.
3. Module should be more user friendly and acknowledge commands.

When a mentor runs `.gci nick`, Begiak should generate a code and print it out, as well as tag the mentor (e.g. "The nick <nick> has been linked to the GCI module by <mentor_nick>. Code: <code>"). We won't need to maintain a list of mentors, as mentors can simply paste the above message on the Task Instance.

After four hours, Begiak should print out the message indicating that the user has completed the task. `.gci_check` should also indicate the details above.

Thanks @Androbin for your work so far!
