### ISSUE TITLE
[greet.py] Tell people about NickServ

### ISSUE THREAD

**Issue by flammie** [apertium/phenny#438]
I think we decided on IRC that begiak should not greet everyone loudly since we have tons of spambots joining all the time.

**Comment by TinoDidriksen** [comment]
It should instead greet them with information on how to register with nickserv, and should do so both as /msg and /notice because clients tend to hide one of those and it's random which one.

**Comment by TinoDidriksen** [comment]
This is high priority. It should be in place and deployed before GCI starts in a week.
