### ISSUE TITLE
Synchronise Begiak with upstream

### ISSUE THREAD

**Issue by wei2912** [apertium/phenny#449]
Begiak is forked from https://github.com/mutantmonkey/phenny. Currently, it is ahead by 1000+ commits and behind by < 100 commits. To keep the codebase up to date, commits from upstream should be pulled if they are relevant to begiak.

Also, in the spirit of FOSS, we should cherry pick some of our commits and submit PRs to the main codebase.

**Comment by Androbin** [comment]
In Progress:
* [ ] https://github.com/mutantmonkey/phenny/pull/49
* [x] https://github.com/mutantmonkey/phenny/pull/82
* [x] https://github.com/mutantmonkey/phenny/pull/85
* [ ] https://github.com/mutantmonkey/phenny/pull/87

**Comment by wei2912** [comment]
@mutantmonkey has archived upstream, so I don't think the project is being actively maintained anymore. Hence, I've decided to close this issue.

**Comment by sushain97** [comment]
Hmmm:

> My fork of phenny lives on at https://github.com/vtluug/phenny. This tree is now unmaintained.

**Comment by Androbin** [comment]
One can ask GitHub Support to remove a fork pointer to turn it standalone repository.
Maybe we can ask them to instead change our fork pointer from mutantmonkey to vtluug?
