### ISSUE TITLE
quoted-unreadable names should be decoded

### ISSUE THREAD

**Issue by flammie** [apertium/phenny#479]
begiak doesn't decode quoted-unreadable names when announcing mail messages, e.g.:

```
06:15  begiak> apertium-stuff: =?UTF-8?Q?Sevilay_Bayatl=C4=B1?= <se...@gm....com>: Re: Fwd: RBMT from Kazakh to Turkish
11:16  begiak> apertium-stuff: =?UTF-8?B?SMOoY3RvciBBbMOycyBpIEZvbnQ=?= <he...@gm....com>: Re: Fwd: RBMT from Kazakh to Turkish
```

**Comment by jonorthwash** [comment]
Duplicate of #260.

**Comment by jonorthwash** [comment]
@Androbin, do you know why your fix isn't working?

**Comment by tomasff** [comment]
I tried @Androbin 's fix in a simple script with the sample text mentioned above and it worked. Not sure why it wasn't working in the bot. I tried it another way which also worked with the sample text, but wasn't able to test in the actual bot.

**Comment by Androbin** [comment]
I think I got it: `e['Subject']` is processed correctly but `e['From']` is not. We just need to do the same for the other field(s).
