### ISSUE TITLE
Support Capitalized "Tell"

### ISSUE THREAD

**Issue by AMR-KELEG** [apertium/phenny#488]
Begiak is currently only triggered to pass reminders if lower-cased "tell" is used.
Can we also extend it to be triggered by upper-cased "Tell"?

**Comment by jonorthwash** [comment]
Should be trivial to make it case-insensitive.

**Comment by scoopgracie** [comment]
Done in PR#493 https://github.com/apertium/phenny/pull/493

**Comment by jonorthwash** [comment]
Is this issue now closed?

**Comment by wei2912** [comment]
IMHO for consistency's sake we ought to just remain with status quo. If we wish to make "tell" case-insensitive then we should change all other commands too, otherwise it may lead to confusion for users. However, I can't see any easy way to make all commands case insensitive.

**Comment by scoopgracie** [comment]
I'll close my PR. Consensus seems to be what @wei2912 suggests.
