### ISSUE TITLE
opt out from "Consider rmoving" messages?

### ISSUE THREAD

**Issue by flammie** [apertium/phenny#489]
I use Flammie[m]  for matrix account and Flammie for irssi. I don't need new message every day that I can consider removing the [m].
![consider-removing](https://user-images.githubusercontent.com/1498282/68674852-f8570400-0556-11ea-995a-d1a06ae583e1.png)

**Comment by scoopgracie** [comment]
What about just doing away with those messages entirely? Are they really helpful?

**Comment by jonorthwash** [comment]
We could have a "snooze" feature for this maybe?  Or just like "permanently dismiss"?

**Comment by scoopgracie** [comment]
What is the use for the messages? Is the [m] really problematic?

**Comment by flammie** [comment]
> We could have a "snooze" feature for this maybe? Or just like "permanently dismiss"?

I'd prefer permanently dismiss, as I cannot follow the advice anyways. I can see it will be useful for first time matrix users with no irc experience once.

**Comment by scoopgracie** [comment]
How about only when user is first seen?

**Comment by jonorthwash** [comment]
> How about only when user is first seen?

A user could miss it the first few times.  Perhaps just add "Tell begiak 'dismiss' to not see this message again." to the end of the message and have that work.

**Comment by scoopgracie** [comment]
Fixed by #506.

**Comment by jonorthwash** [comment]
@flammie, please test and report back :)

**Comment by flammie** [comment]
seems to work thanks.
