### ISSUE TITLE
More begiak tasks on GCI

### ISSUE THREAD

**Issue by scoopgracie** [apertium/phenny#494]
I think putting more begiak-related tasks on GCI would be helpful. Not everybody can contribute to the translator, since doing much on it requires knowing two languages.

**Comment by mr-martian** [comment]
Look at the issues labeled gci: https://github.com/apertium/phenny/issues?q=is%3Aissue+is%3Aopen+label%3Agci

I think #491 especially, since that's causing most of the failing tests.

I'll turn then into actual GCI tasks when I get the chance.

**Comment by scoopgracie** [comment]
ok, thx!
