### ISSUE TITLE
Set a coding style

### ISSUE THREAD

**Issue by scoopgracie** [apertium/phenny#495]
There really is no official coding style for Begiak. Everyone seems to follow PEP8, so should we make that official?

**Comment by wei2912** [comment]
Yeah, by default the Python community as a whole follows PEP8 and will impose additional restrictions on top of it. In our case, given the pretty decentralised nature of begiak development (where most development is done by GCI students, with each working on a few modules), I don't think there's a strong need to create a style guide. Honestly most of the scripts are hacked together anw

**Comment by scoopgracie** [comment]
OK. Is that why there are so few commits?

**Comment by wei2912** [comment]
Pretty much why - we only modify the code if it's important to the channel and urgent. Of course you could continue working on the bot after GCI ends if you're interested, or try to develop your own.

**Comment by scoopgracie** [comment]
OK. Do good PRs generally get accepted somewhat quickly?

**Comment by wei2912** [comment]
If we have time to review it... :P Anyways, I'll be closing this issue.
