### ISSUE TITLE
Add an "autotell"?

### ISSUE THREAD

**Issue by scoopgracie** [apertium/phenny#498]
This would make it so that messages in the form:
* nick: message
* nick message
* nick, message
would be equivalent to:
begiak: tell nick message
if **and only if** nick was offline.
Should we do it?

**Comment by TinoDidriksen** [comment]
No, that's way too ambiguous and would be caught by random lines and pastes. The bot must be invoked directly.

**Comment by scoopgracie** [comment]
OK, thanks!
