### ISSUE TITLE
begiak can(not) pester itself

### ISSUE THREAD

**Issue by scoopgracie** [apertium/phenny#500]
One time, I chatted:
begiak: pester begiak tell scoopgracie gracie is a cat
Today, @firespeaker sent me some logs:

    (13:12:44) begiak: Error in 'pester/pester' with input 'begiak: (2019-12-04 02:26:54) scoopgracie pesters you tell scoopgracie gracie is a cat'
    (13:13:11) begiak: sqlite3.OperationalError: database is locked
    (13:13:12) begiak: File "/home/begiak/phenny/modules/pester.py", line 96, in pester
    (13:13:41) begiak: Error in 'pester/pester' with input 'File "/home/begiak/phenny/modules/gci.py", line 138, in linking'
    (13:13:42) begiak: sqlite3.OperationalError: database is locked

Since then, pester does not work. I broke pester.

**Comment by scoopgracie** [comment]
UPDATE: I didn't just break pester. I _completely_ broke begiak. @jonorthwash restarted it and it works again.

**Comment by jonorthwash** [comment]
Getting this now, associated with sporadic rejoins.
```
ERROR: Traceback (most recent call last):
  File "/home/begiak/phenny/bot.py", line 250, in call
    rephrase_errors(func, phenny, input)
  File "/home/begiak/phenny/tools.py", line 223, in rephrase_errors
    return fn(*args, **kw)
  File "/home/begiak/phenny/modules/pester.py", line 96, in pester
    (current_time, inputnick, pesterer, reason))
sqlite3.OperationalError: database is locked
```

**Comment by scoopgracie** [comment]
weird... nobody used pester to trigger that.

**Comment by wei2912** [comment]
@jonorthwash What's the output when the commands [here(https://stackoverflow.com/questions/151026/how-do-i-unlock-a-sqlite-database) are executed?
