### ISSUE TITLE
Disable botsnack

### ISSUE THREAD

**Issue by scoopgracie** [apertium/phenny#512]
It's easy to get carried away with botsnack. (I must admit, I've done it.) It serves no practical use, so should we disable it?

**Comment by jonorthwash** [comment]
Perhaps incorporating it into begiak's generalised(?) rate limiting stuff might be a less extreme approach.

**Comment by scoopgracie** [comment]
OK, but why does it even exist? Does it do anything useful?

**Comment by jonorthwash** [comment]
("Occasional fun" is still a purpose ☺  Also, in the right context it can be nice to show your appreciation to begiak for doing something nice for you...;)

**Comment by scoopgracie** [comment]
ok, sounds good!

**Comment by scoopgracie** [comment]
It already has some built-in rate limiting, maybe make it stricter? begiak
eventually "explodes" (not literally, of course) when you feed it too much.
Maybe make this happen sooner?

**Comment by wei2912** [comment]
This rate limiting should be done for _all_ commands, and not just botsnack. (I can't remember if there's any rate limiting built in, but there's probably a crude `time.sleep()` somewhere.) Since this module is pretty fun and doesn't do much harm, I'll be closing this issue.
