### ISSUE TITLE
Switch to a Sopel base

### ISSUE THREAD

**Issue by scoopgracie** [apertium/phenny#527]
Phenny is outdated. The latest compatible bot is [Sopel](https://sopel.chat/). We should probably switch to Sopel and port any incompatible modules.

See https://gist.github.com/scoopgracie/c5642a1c0d134849ed4dfce1c1c08876 for a diagram. As you can see, Begiak is still on the original phenny (albeit a port to Python 3).

**Comment by sushain97** [comment]
I seriously doubt we'd be able to switch to Sopel as a base... there's probably a couple hundred lines of code that are still the same. What we could do is adopt a fork of Sopel with our modules added and upstream them as appropriate. But that is a bit of an undertaking.

**Comment by scoopgracie** [comment]
OK. Do you think using Sopel rather than Phenny is even necessary, or do you think this would just be a waste of time?

**Comment by wei2912** [comment]
I personally think it's only worth it if Sopel offers features or modules that are very much needed in #apertium. As far as I can tell, Sopel does cover a lot of functionality that has been broken for a while (e.g. search, GitHub), and I like that it's being actively developed, but we'll have to see how we can pull changes from upstream and submit PRs for our modules.

Also, Sopel doesn't seem to have any advanced flood protection logic (see https://github.com/sopel-irc/sopel/issues/1559). We'll want to incorporate that functionality as some of our modules may cause a lot of spam in a channel.

**Comment by wei2912** [comment]
I also don't see any harm in creating a fork of Sopel now and trying to port a few modules over, just to test things out.

**Comment by scoopgracie** [comment]
OK.

**Comment by scoopgracie** [comment]
I researched Sopel, and it does not appear that it would be feasible. Sopel has diverged too far from phenny.
