### ISSUE TITLE
Add Python 3.5 to Travis CI

### ISSUE THREAD

**Issue by scoopgracie** [apertium/phenny#541]
We don't test on Python 3.5, only 3.6 and up. 3.5 is still supported, and is the only version in Debian Buster's repos, so I'd say it's important.

**Comment by HAKSOAT** [comment]
I'll like to do this

**Comment by wei2912** [comment]
> I'll like to do this

Feel free to submit a PR if you'd like - editing https://github.com/apertium/phenny/blob/master/.travis.yml with a one-liner should be sufficient.
