### ISSUE TITLE
Disable module fcc

### ISSUE THREAD

**Issue by scoopgracie** [apertium/phenny#542]
What does a call sign lookup have to do with Apertium?

**Comment by jonorthwash** [comment]
Some of us are amateur radio operators :)

**Comment by scoopgracie** [comment]
But do FCC lookups belong in #apertium?

**Comment by jonorthwash** [comment]
I don't see a major problem with it, but I'm probably the wrong person to ask.

**Comment by scoopgracie** [comment]
Okay. I just don't get the point of having a non-just for fun command that
really has nothing to do with apertium.
